### ISSUE TITLE
Initiate the repository

### ISSUE THREAD

**Issue by wesleydebruijn** [Frutch/artogo-android-user#1]
Create the Android project.
Also, configure the .gitignore so only the things that need to be pushed are pushed on the repository.

**Comment by guillaumejparis** [comment]
Done.
.gitignore : 

*.iml
.gradle
/local.properties
/.idea/workspace.xml
/.idea/libraries
.DS_Store
/build
/captures
# Built application files
*.apk
*.ap_

# Files for the Dalvik VM
*.dex

# Java class files
*.class

# Generated files
bin/
gen/
out/

# Gradle files
.gradle/
build/

# Local configuration file (sdk path, etc)
local.properties

# Proguard folder generated by Eclipse
proguard/

# Log Files
*.log

# Android Studio Navigation editor temp files
.navigation/

# Android Studio captures folder
captures/

#Keystore files
*.jks
