### ISSUE TITLE
Main activity

### ISSUE THREAD

**Issue by wesleydebruijn** [Frutch/artogo-android-user#3]
This activity will be shown after the app is started (after logo activity).

_Still be determined what this activity must show_

**Comment by guillaumejparis** [comment]
MainActivity created + navbar.
![screenshot_20160314-193955](https://cloud.githubusercontent.com/assets/4204277/13755703/bc754f40-ea1c-11e5-861a-0a33a26d9ab3.png)

**Comment by guillaumejparis** [comment]
Work on Fragment Manager
